### ISSUE TITLE
Unable to take save a ReSpec oma-profiel file

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/Tools#10]
The saving operation as described in the Document Editing Guidelines:
https://openmobilealliance.atlassian.net/wiki/pages/viewpage.action?pageId=2949263

is not working.
There is no option to get to step 3)

**Comment by jmudge** [comment]
None of the following 3 ReSpec menu items work (using FIrefox and IE):
Save Snapshot
About ReSpec
Search Specref DB

It would be good if these could be made to work again.

**Comment by drew** [comment]
fixed in https://github.com/OpenMobileAlliance/Tools/commit/96e64feb2df22ebce9e74cedcc6d0e87353839da

works on stable and wip
