### ISSUE TITLE
Images and the ReSpec static snapshots

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/Tools#9]
It seems that when a ReSpec static snapshot is created the images are not included in the file that is generated. How is the storage of the images going to be handled? Will unique publically available URLs be required for all the images?

**Comment by jpradocueva** [comment]
We tried to save a document as a build HTML and the images are not part of the file.

**Comment by drew** [comment]
such is the nature of html. this will have to be taken into account during the publication process.
